/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Aranzman;
import domen.Klijent;
import domen.OpstiDomenskiObjekat;
import domen.Prodavac;
import domen.Racun;
import domen.StavkaRacuna;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleStavke;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Lenovo
 */
public class UnesiRacun extends javax.swing.JDialog {

    /**
     * Creates new form UnesiRacun
     */
    public UnesiRacun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblStavke.setModel(new ModelTabeleStavke());
        popuniKlijente();
        popuniAranzmanje();
        izracunajUkupno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbKlijenti = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtUkupnaVrednost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbAranzmani = new javax.swing.JComboBox();
        txtPopust = new javax.swing.JTextField();
        txtIznosStavke = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Klijent");

        cmbKlijenti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Ukupna vrednost");

        txtUkupnaVrednost.setEditable(false);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jLabel3.setText("Aranzman");

        jLabel4.setText("Popust");

        jLabel5.setText("Iznos");

        cmbAranzmani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Dodaj stavku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Obrisi stavku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SACUVAJ RACUN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbAranzmani, 0, 184, Short.MAX_VALUE)
                                    .addComponent(txtPopust)
                                    .addComponent(txtIznosStavke)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKlijenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUkupnaVrednost))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbAranzmani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIznosStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Aranzman a = (Aranzman) cmbAranzmani.getSelectedItem();
        int popust = Integer.parseInt(txtPopust.getText());
        double iznos = Double.parseDouble(txtIznosStavke.getText());

        StavkaRacuna sr = new StavkaRacuna(-1, null, a, popust, iznos);

        ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
        List<OpstiDomenskiObjekat> lista = mts.getLista();

        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            StavkaRacuna srTabela = (StavkaRacuna) opstiDomenskiObjekat;
            if (srTabela.getAranzman().getSifraAranzmana() == a.getSifraAranzmana()) {
                JOptionPane.showMessageDialog(this, "Stavka za ovaj aranzman vec postoji za ovaj racun");
                return;
            }
        }

        mts.dodaj(sr);
        izracunajUkupno();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int red = tblStavke.getSelectedRow();
        if (-1 != red) {
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
            mts.obrisi(red);
            izracunajUkupno();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
        Klijent klijent = (Klijent) cmbKlijenti.getSelectedItem();
        double ukupno = Double.parseDouble(txtUkupnaVrednost.getText());
        List<OpstiDomenskiObjekat> lista = mts.getLista();
        Prodavac prodavac = ((GlavnaForma) getParent()).getUlogovaniProdavac();

        Racun racun = new Racun(-1, klijent, prodavac, new Date(), ukupno, lista);

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.SACUVAJ_RACUN, racun);
        Komunikacija.getInstanca().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstanca().primiOdgovor();
        
        JOptionPane.showMessageDialog(this, so.getPoruka());

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnesiRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnesiRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnesiRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnesiRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnesiRacun dialog = new UnesiRacun(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAranzmani;
    private javax.swing.JComboBox cmbKlijenti;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtIznosStavke;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtUkupnaVrednost;
    // End of variables declaration//GEN-END:variables

    private void popuniKlijente() {
        Klijent k = new Klijent();
        k.setImeKlijenta("");

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.PRETRAGA_KLIJENTA, k);
        Komunikacija.getInstanca().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstanca().primiOdgovor();

        List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) so.getOdgovor();

        cmbKlijenti.removeAllItems();

        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            cmbKlijenti.addItem(opstiDomenskiObjekat);
        }
    }

    private void popuniAranzmanje() {
        Aranzman a = new Aranzman();
        a.setDestinacija("");

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.PRETRAZI_ARANZMAN, a);
        Komunikacija.getInstanca().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstanca().primiOdgovor();

        List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) so.getOdgovor();

        cmbAranzmani.removeAllItems();

        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            cmbAranzmani.addItem(opstiDomenskiObjekat);
        }
    }

    private void izracunajUkupno() {
        ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
        double ukupno = 0.00;

        List<OpstiDomenskiObjekat> lista = mts.getLista();

        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            StavkaRacuna srTabela = (StavkaRacuna) opstiDomenskiObjekat;
            ukupno += srTabela.izracuanIznosSaPopustom();
        }

        txtUkupnaVrednost.setText("" + ukupno);
    }
}
